### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by smagedy** [dkruyt/ginlong-scraper#11]
Hi,
I had some other isues and now i I'm trying to get it working again with the new script. 
I get the next error:
```
Traceback (most recent call last):
  File "ginlong-scraper.py", line 326, in <module>
    get_loglevel = os.environ['LOG_LEVEL']
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOG_LEVEL'
```
Can you help me?

**Comment by dkruyt** [comment]
What is your Log_level value in your environment?

**Comment by smagedy** [comment]
how can i find that? i'm running raspbian on a raspberry,
Is this what you mean ?
`-rw-r----- 1 root     adm       33592 Dec 25 11:36 syslog`

**Comment by dkruyt** [comment]
How did you start the docket container? With what options?

**Comment by smagedy** [comment]
I'm starting it with the next command:
python3 ginlong-scraper.py  aswell with sudo

**Comment by jturnbull** [comment]
You've not set any enviroment variables. LOG_LEVEL is the first to check, so it's falling over then but you have to set all the others listed in the README too.

See here for Python env variables: https://medium.com/dataseries/hiding-secret-info-in-python-using-environment-variables-a2bab182eea
